spring.application.name=billetera

# Conexión al contenedor PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/billetera
spring.datasource.username=admin
spring.datasource.password=root

# Configuración de Hibernate (El motor ORM)
# 'update' creará las tablas automáticamente basándose en nuestro código Java
spring.jpa.hibernate.ddl-auto=update
# Esto imprimirá en consola las sentencias SQL que Spring genere por debajo
spring.jpa.show-sql=true
