CREATE TABLE cuentas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titular VARCHAR(255),
    saldo NUMERIC(38, 2)
);

CREATE TABLE transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_destino_id BIGINT,
    cuenta_origen_id BIGINT,
    fecha TIMESTAMP(6),
    monto NUMERIC(38, 2),
    tipo VARCHAR(255),
    CONSTRAINT fk_transacciones_cuenta_destino
        FOREIGN KEY (cuenta_destino_id) REFERENCES cuentas (id),
    CONSTRAINT fk_transacciones_cuenta_origen
        FOREIGN KEY (cuenta_origen_id) REFERENCES cuentas (id)
);
