CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(32) NOT NULL UNIQUE,
    password_hash VARCHAR(100),
    habilitado BOOLEAN NOT NULL DEFAULT FALSE
);

-- El propietario heredado se mantiene deshabilitado hasta configurar DEMO_USER_PASSWORD.
INSERT INTO usuarios (id, nombre_usuario, password_hash, habilitado)
VALUES (1, 'demo', NULL, FALSE);

SELECT setval(pg_get_serial_sequence('usuarios', 'id'), 1, TRUE);

ALTER TABLE cuentas ADD COLUMN usuario_id BIGINT;
UPDATE cuentas SET usuario_id = 1;
ALTER TABLE cuentas ALTER COLUMN usuario_id SET NOT NULL;
ALTER TABLE cuentas
    ADD CONSTRAINT fk_cuentas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id);
CREATE INDEX idx_cuentas_usuario_id ON cuentas (usuario_id);
